import localFont from "next/font/local";
import "./globals.css";
import Header from "./Header";
import OuterLayout from "@/components/layouts/OuterLayout";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`place-items-center text-center`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
